### ISSUE TITLE
Bookmarklet clipping image issue in Chrome

### ISSUE THREAD

**Issue by bezidejni** [ccnmtl/mediathread#26]
Using Chrome 29.0.1547.57, when I go to the image page (direct image link) and try to clip the image, the popup shows as it should and it recognizes the image. The problem is when I click the analyze button (form submit), the whole tab just crashes.

Here's the image I was testing with: http://i.imgur.com/fpark.jpg

Clipping of the same image works in Firefox without any problems. Also, clipping works if you're not on a direct image url page, but on the "wrapper" page: http://imgur.com/fpark/

Attached is the screenshot of the crash as well:
![fpark jpg__728484_](https://f.cloud.github.com/assets/38059/1028181/7c497bb4-0e80-11e3-9d88-e8b6d671674c.png)

**Comment by nikolas** [comment]
I'm closing this - the bookmarklet is now deprecated in favor of our browser extensions. The chrome extension is [here](https://chrome.google.com/webstore/detail/mediathread/gambcgmmppeklfmbahomokogelnaffbi).
