### ISSUE TITLE
Move CollectionListView to material-ui table

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/mediathread#4648]
This table currently uses react-data-table-component, which doesn't use semantic table elements.

This library from Google looks good: https://mui.com/material-ui/react-table/

**Comment by ndittren** [comment]
I can take this on for this sprint.

**Comment by nikolas** [comment]
This is proving to be pretty involved to change, actually. And I did notice that our existing setup does use ARIA elements like role="table", role="columnheader", which should allow screenreaders to properly understand what's going on in this table. I think this deserves another look here - not sure if it's exactly "Critical".

**Comment by nikolas** [comment]
Copied from my note on Natalia's PR here: #4675

So, after looking at this problem from a few angles, (I even have a branch [here](https://github.com/ccnmtl/mediathread/tree/data-table-semantic) that updates the existing library to use `<table>` and `<tr>` elements), I think our current table setup here may be okay. Through attempting to re-implement sorting with different libraries, I'm realizing this is a problem that merits a bigger timeframe than we currently have to work with for these changes.

Although the react-data-table-component table is using divs, ARIA roles are defined properly, so this should suffice for screen readers.
