### ISSUE TITLE
Accessibility issue: Provide an informative context-sensitive page title

### ISSUE THREAD

**Issue by karentsao** [ccnmtl/mediathread#5158]
**Module**:
Collection Detail: Video Type

**Violation**:
Provide an informative context-sensitive page title

**Description**:
[Pattern: Page Title]

[Issue]
This page lacks a unique page title (<title>).

[User Impact]
When the page <title> of the document does not describe the topic or purpose of the page, users of assistive technology may have trouble finding content or orient themselves.

*Major Sheet Row 11, 15, 16 in https://docs.google.com/spreadsheets/d/1L9mwZ55UNKOUOVC_w-fuUjpbeNTyXVE5/edit#gid=512445576

**Comment by dc3788** [comment]
@karentsao Is it possible to provide the path of the page you are referring to?

**Comment by karentsao** [comment]
Sure. 

For example, https://mediathread-qa.stanford.edu/course/53/react/asset/287/. You can see it has "<title>Mediathread Home</title>" for this page, but the main page https://mediathread-qa.stanford.edu/course/53/ also has "<title>Mediathread Home</title>".

**Comment by nikolas** [comment]
This was addressed here: https://github.com/ccnmtl/mediathread/pull/5218
